version: '3'
services:
  service_jekyll:
    image: jekyll/jekyll:3.8
    container_name: local_jekyll
    volumes:
        - ./:/usr/src/app
    # command: sh -c 'jekyll serve -s /usr/src/app --watch'
    command: /bin/bash
    ports:
      - '4000:4000'
    tty: true